import express from 'express'; import Database from 'better-sqlite3'; import crypto from 'crypto';
const app=express(); app.use(express.json()); app.use(express.static('public'));
const db=new Database('roasterlee.db');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,role TEXT,status TEXT); CREATE TABLE IF NOT EXISTS blends(code TEXT PRIMARY KEY,recipe TEXT); CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,customer TEXT,blend TEXT,kg REAL,status TEXT DEFAULT 'Pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const OWNER=401102212; db.prepare('INSERT OR IGNORE INTO users VALUES(?,?,?,?)').run(OWNER,'Owner','admin','approved');
db.prepare('INSERT OR IGNORE INTO blends VALUES(?,?)').run('BV55',JSON.stringify({Brazil:.5,'Robusta Vietnam':.5})); db.prepare('INSERT OR IGNORE INTO blends VALUES(?,?)').run('LV55',JSON.stringify({Laos:.5,'Robusta Vietnam':.5}));
function verify(initData){ if(process.env.DEV_MODE==='true') return {id:OWNER,first_name:'Owner'}; if(!initData||!process.env.BOT_TOKEN)return null; const p=new URLSearchParams(initData),hash=p.get('hash');p.delete('hash'); const data=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n'); const secret=crypto.createHmac('sha256','WebAppData').update(process.env.BOT_TOKEN).digest(); const calc=crypto.createHmac('sha256',secret).update(data).digest('hex'); if(calc!==hash)return null; try{return JSON.parse(p.get('user'))}catch{return null}}
app.use('/api',(req,res,next)=>{const u=verify(req.headers['x-telegram-init-data']);if(!u)return res.status(401).json({error:'Open this app from Telegram.'}); const row=db.prepare('SELECT * FROM users WHERE id=?').get(u.id); if(!row){db.prepare('INSERT OR IGNORE INTO users VALUES(?,?,?,?)').run(u.id,[u.first_name,u.last_name].filter(Boolean).join(' '),'staff','pending');return res.status(403).json({error:'Access request sent. Ask the owner to approve you.'})} if(row.status!=='approved')return res.status(403).json({error:'Waiting for owner approval.'});req.user=row;next()});
app.get('/api/state',(req,res)=>res.json({me:req.user,blends:db.prepare('SELECT * FROM blends').all().map(x=>({...x,recipe:JSON.parse(x.recipe)})),orders:db.prepare('SELECT * FROM orders ORDER BY id DESC').all(),users:req.user.role==='admin'?db.prepare('SELECT * FROM users ORDER BY status,name').all():[]}));
app.post('/api/orders',(req,res)=>{const {customer,blend,kg}=req.body;if(!customer||!blend||!(+kg>0))return res.status(400).json({error:'Customer, blend and kg are required.'});db.prepare('INSERT INTO orders(customer,blend,kg) VALUES(?,?,?)').run(customer,blend,+kg);res.json({ok:true})});
app.patch('/api/orders/:id',(req,res)=>{db.prepare('UPDATE orders SET status=? WHERE id=?').run(req.body.status,req.params.id);res.json({ok:true})});
app.delete('/api/orders/:id',(req,res)=>{if(req.user.role!=='admin')return res.sendStatus(403);db.prepare('DELETE FROM orders WHERE id=?').run(req.params.id);res.json({ok:true})});
app.post('/api/blends',(req,res)=>{if(req.user.role!=='admin')return res.sendStatus(403);const {code,recipe}=req.body; const sum=Object.values(recipe||{}).reduce((a,b)=>a+(+b||0),0);if(!code||Math.abs(sum-1)>.001)return res.status(400).json({error:'Blend ratios must total 100%.'});db.prepare('INSERT OR REPLACE INTO blends VALUES(?,?)').run(code.toUpperCase(),JSON.stringify(recipe));res.json({ok:true})});
app.patch('/api/users/:id',(req,res)=>{if(req.user.role!=='admin')return res.sendStatus(403);db.prepare('UPDATE users SET status=? WHERE id=?').run(req.body.status,req.params.id);res.json({ok:true})});
const port=process.env.PORT||3000;app.listen(port,()=>console.log('RoasterLee running on '+port));
